seed_file = File.join(Rails.root, 'db', 'seeds.yml')
config = YAML::load_file(seed_file)
Role.create(config["roles_list"])
User.create(config["user_list"])
Room.create!(config["room_list"])
Group.create!(config["group_list"])
Memberlist.create!(config["memberlist_list"])
Order.create!(config["order_list"])
Assigment.create!(config["assigment_list"])